/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsVoiceRouteImport } from './routes/settings.voice'
import { Route as DocIdRouteImport } from './routes/doc.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVoiceRoute = SettingsVoiceRouteImport.update({
  id: '/settings/voice',
  path: '/settings/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocIdRoute = DocIdRouteImport.update({
  id: '/doc/$id',
  path: '/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/voice': typeof SettingsVoiceRoute
  '/doc/$id': typeof DocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/settings/voice' | '/doc/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/settings/voice' | '/doc/$id'
  id: '__root__' | '/' | '/settings' | '/settings/voice' | '/doc/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SettingsVoiceRoute: typeof SettingsVoiceRoute
  DocIdRoute: typeof DocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/voice': {
      id: '/settings/voice'
      path: '/settings/voice'
      fullPath: '/settings/voice'
      preLoaderRoute: typeof SettingsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$id': {
      id: '/doc/$id'
      path: '/doc/$id'
      fullPath: '/doc/$id'
      preLoaderRoute: typeof DocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SettingsVoiceRoute: SettingsVoiceRoute,
  DocIdRoute: DocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
